# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build and publish a Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: Release

on:
  push:
    tags: [ "v*.*.*" ]

jobs:

  test:

    uses: ./.github/workflows/test.yml

  publish:

    needs: test

    strategy:
      matrix:
        self-contained:
        - pivot: self-contained
          option: --self-contained
        - pivot: framework-dependent
          option: --no-self-contained
        RID:
        - win-x64
        - win-arm64

    name: publish-${{ matrix.self-contained.pivot }}-${{ matrix.RID }}

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.1
      with:
        fetch-depth: 1

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5.0.1
      with:
        dotnet-version: 10.0
        dotnet-quality: ga

    - name: Publish
      run: |
        dotnet publish RunHideInTrayConsole --output artifacts\publish\release ${{ matrix.self-contained.option }} --property:PublishReadyToRun=true --runtime ${{ matrix.RID }}
        dotnet publish RunHideInTrayWinForms --output artifacts\publish\release ${{ matrix.self-contained.option }} --property:PublishReadyToRun=true --runtime ${{ matrix.RID }}

    - name: Zip artifacts
      run: |
        cd artifacts
        Compress-Archive publish\release -DestinationPath RunHideInTray_${{ matrix.self-contained.pivot }}_${{ matrix.RID }}.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v5.0.0
      with:
        name: RunHideInTray_${{ matrix.self-contained.pivot }}_${{ matrix.RID }}
        path: artifacts\RunHideInTray_${{ matrix.self-contained.pivot }}_${{ matrix.RID }}.zip
  
  release:

    needs: publish

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.1
      with:
        fetch-depth: 1

    - name: Download artifacts
      uses: actions/download-artifact@v6.0.0
      with:
        merge-multiple: true

    - name: Create Github Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create --draft ${{ github.ref_name }} --title ${{ github.ref_name }} --notes-from-tag \
        "RunHideInTray_self-contained_win-x64.zip#RunHideInTray self-contained x64" \
        "RunHideInTray_self-contained_win-arm64.zip#RunHideInTray self-contained ARM64" \
        "RunHideInTray_framework-dependent_win-x64.zip#RunHideInTray framework-dependent x64" \
        "RunHideInTray_framework-dependent_win-arm64.zip#RunHideInTray framework-dependent ARM64"
